# Generated by Django 5.2.17 on 2026-09-14 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=160)),
                ('institution', models.CharField(max_length=180)),
                ('year', models.CharField(max_length=40)),
                ('result', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['-display_order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=160)),
                ('position', models.CharField(max_length=160)),
                ('duration', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('technologies', models.CharField(blank=True, max_length=240)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Experience',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Arshit Gondaliya', max_length=120)),
                ('title', models.CharField(default='Software Engineer | Web Developer | Data Analytics', max_length=180)),
                ('description', models.TextField()),
                ('about_text', models.TextField(blank=True)),
                ('location', models.CharField(default='Surat, Gujarat, India', max_length=160)),
                ('phone', models.CharField(default='+91 8200993607', max_length=30)),
                ('email', models.EmailField(default='arshitgondaliya09@gmail.com', max_length=254)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/')),
                ('about_image', models.ImageField(blank=True, upload_to='profile/')),
                ('contact_image', models.ImageField(blank=True, upload_to='profile/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio profile',
                'verbose_name_plural': 'Portfolio profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('technologies', models.CharField(max_length=320)),
                ('project_image', models.ImageField(blank=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('live_demo_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('data', 'Data Science & ML'), ('web', 'Web & Database'), ('tools', 'Tools')], max_length=20)),
                ('icon', models.CharField(default='fa-code', max_length=60)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('icon', models.CharField(default='fa-link', max_length=60)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
    ]
