# Generated by Django 5.2.17 on 2026-09-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seed_resume_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
